### PR TITLE
Fix: per_page param

### LINKED ISSUE #61: Refactor API paging parameter name
In [discussion with Littlepay](https://cal-itp.slack.com/archives/C03V716MKQS/p1712089166817549) over the issues encountered during #53, we learned that [at least for some endpoints](https://cal-itp.slack.com/archives/C03V716MKQS/p1714455629754259?thread_ts=1712089166.817549&cid=C03V716MKQS), the paging parameter is called `per_page` instead of `perPage` as documented.

Here are the endpoints we implement that use paging, and the current parameter name in the docs:

Function | Paging param in docs | Additional notes
-- | -- | --
[`get_concession_groups`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/groups.py#L96) | [`per_page`](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/GetConcessionGroupsList)
[`get_concession_group_linked_funding_sources`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/groups.py#L112) | [`perPage`](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/GetFundingSourcesLinkedToConcessionGroupsList) | [should be `per_page` according to this thread with Littlepay](https://cal-itp.slack.com/archives/C03V716MKQS/p1714455629754259?thread_ts=1712089166.817549&cid=C03V716MKQS)
[`get_concession_group_products`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/products.py#L39) | [`per_page`](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/GetProductsLinkedToConcessionGroupsList)
[`get_products`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/products.py#L46) | [`perPage`](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/GetproductsList) | _no change_
#60 (get list of concession groups linked to a funding source) | [`per_page`](https://docs.littlepay.io/reference/backoffice/tag/Products/#tag/Products/operation/GetConcessionGroupsLinkedToFundingSource) | Done in #62 

## Acceptance criteria

- [ ] Endpoints above that use `per_page` are updated in the code

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #61

### CODE REVIEW

**Comment by angela-tran** [comment]
@thekaveman In `_get_list`, do you think we should remove `perPage` from the `params` dict if `per_page` was passed in as a kwarg?

https://github.com/cal-itp/littlepay/blob/9191b430e6fec6e43462745d2febd8f165b7911a/littlepay/api/client.py#L132-L134

**Comment by angela-tran** [comment]
> > @thekaveman In `_get_list`, do you think we should remove `perPage` from the `params` dict if `per_page` was passed in as a kwarg?
> 
> Yeah that's a good question. I'm not super happy with all these duplicated `per_page` all over the place either. Maybe a different approach is to invert the logic, use `per_page` by default in `_get_list` and pass in the override `perPage` on the (I think only one??) endpoint it is needed.
> 
> It sounds like they are trying to normalize these and so hopefully soon we won't have to worry about the different versions.
> 
> As to your actual question, I don't think it's a problem to send both, and we can save ourselves a few cycles by not worrying about removing it / writing tests etc.

That all makes sense. I can make those changes, thanks for the suggestions 👍

**Comment by thekaveman** [comment]
@angela-tran I merged #62 so if you want to rebase on `main` to get that one as well :+1: :pray:

**Review by thekaveman — APPROVED** [review]
Nice!

**Pull request merged**
