### PR TITLE
Fix: do not raise errors for unexpected fields in responses

### LINKED ISSUE #66: Avoid errors when responses contain additional fields
A pattern in this library is to take JSON returned from the API and use it to hydrate response objects, e.g. `FundingSourceResponse`, `GroupFundingSourceResponse`, etc. See [`_get`](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/client.py#L130), `_post`, and `_put`.

If the JSON contains fields that we didn't define in our response class, currently we'll get a `TypeError`. For example, see cal-itp/benefits#2365.

It would be nice to avoid throwing an error.

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #66 

After going through many different resources online about making dataclasses ignore unexpected fields, my conclusion is that Python's built-in `dataclass` does not provide an easy way to do this, and any attempts to make it work would really just defeat the purpose of using a dataclass in the first place.

[Pydantic has a `dataclass`](https://docs.pydantic.dev/latest/concepts/dataclasses/#dataclass-config) that builds on top of Python's which allows you to ignore extra fields, but when I tried it out, that caused new unrelated errors due to Pydantic performing type validation.

This PR implements the simplest and most straightforward solution, which is to just use a class. This allows us to specify a `**kwargs` parameter in the `__init__` method, which is where unexpected fields will get passed into and not cause any error.

### CODE REVIEW

**Comment by angela-tran** [comment]
If anyone finds a way to do it with dataclasses, I will happily implement

**Comment by angela-tran** [comment]
Here are some of the resources I read through:

- https://stackoverflow.com/questions/55099243/python3-dataclass-with-kwargsasterisk
- https://stackoverflow.com/questions/54678337/how-does-one-ignore-extra-arguments-passed-to-a-dataclass
- https://dnmtechs.com/ignoring-extra-arguments-in-a-python-3-dataclass/ - the `__post_init__` idea seemed very simple, but it change anything when I tried it
- https://hatchjs.com/pydantic-ignore-extra-fields/
- https://old.reddit.com/r/learnpython/comments/1f8u219/is_it_possible_to_ignore_some_fields_when/

**Comment by angela-tran** [comment]
This page has an interesting idea with assigning the JSON response to `__dict__`, but then there are no explicit fields on any of the classes...

https://stackoverflow.com/questions/15476983/deserialize-a-json-string-to-an-object-in-python

**Comment by thekaveman** [comment]
@angela-tran we can talk more in stand up, but I wonder if this idea makes more sense, and would still give us the benefits of a `@dataclass`: https://stackoverflow.com/a/55101438

> If you care about accessing attributes by name, or if you can't distinguish between known and unknown arguments during initialisation, then your last resort without rewriting `__init__` (which pretty much defeats the purpose of using dataclasses in the first place) is writing a `@classmethod`

We would need to alter our [response parsing code](https://github.com/cal-itp/littlepay/blob/main/littlepay/api/client.py#L160) which could look a little gnarly... but it seems like it might outweigh having to define all these classes by hand.

**Comment by thekaveman** [comment]
This idea with a `_post_init_` method seems too good to be true... I assume that didn't work as advertised? 

https://dnmtechs.com/ignoring-extra-arguments-in-a-python-3-dataclass/

**Comment by angela-tran** [comment]
Closing this in favor of a different approach that still uses dataclasses

**Pull request closed without merging**
